# Generated by Django 4.2 on 2024-07-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0002_client_contract_item_project_section_task_userpreset_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
