# Generated by Django 4.2 on 2024-07-12 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_user_dark_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
