# Generated by Django 4.2 on 2024-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_item_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="budget",
            field=models.FloatField(default=0.0),
        ),
    ]
