# Generated by Django 4.2 on 2024-07-12 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_item_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="section",
            field=models.ManyToManyField(
                related_name="contracts", to="tracker.section"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="project",
            name="contract",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tracker.contract"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="section",
            name="Item",
            field=models.ManyToManyField(related_name="sections", to="tracker.item"),
        ),
        migrations.AlterField(
            model_name="section",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
