# Generated by Django 4.2 on 2024-07-19 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_contract_section_alter_contract_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SectionLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="contract",
            name="section",
            field=models.ManyToManyField(to="tracker.section"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="project",
            name="contract",
            field=models.ManyToManyField(blank=True, to="tracker.contract"),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="section",
            name="Item",
            field=models.ManyToManyField(to="tracker.item"),
        ),
        migrations.AlterField(
            model_name="section",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="TaskLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tracker.itemlibrary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemlibrary",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="tracker.sectionlibrary",
            ),
        ),
    ]
