# Generated by Django 4.2 on 2024-07-19 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0007_itemlibrary_sectionlibrary_alter_contract_section_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemlibrary",
            old_name="item_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="sectionlibrary",
            old_name="section_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tasklibrary",
            old_name="task_name",
            new_name="name",
        ),
    ]
