# Generated by Django 4.2 on 2024-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_rename_item_name_itemlibrary_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="Item_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.CharField(max_length=255),
        ),
    ]
