# Generated by Django 4.2 on 2024-07-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_alter_contract_contract_name_alter_item_item_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.client",
            ),
        ),
    ]
