# Generated by Django 4.2 on 2024-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_alter_project_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionlibrary",
            name="section_billed_hourly",
            field=models.BooleanField(default="False"),
        ),
    ]
