# Generated by Django 4.2 on 2024-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_sectionlibrary_section_billed_hourly"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="budget",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="item",
            name="rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="item",
            name="total",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[("hours", "Hours"), ("item", "Item")],
                default="hours",
                max_length=10,
            ),
        ),
    ]
