# Generated by Django 4.2 on 2024-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0013_alter_item_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
