# Generated by Django 4.2 on 2024-08-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0015_alter_logs_log_item_alter_logs_log_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="log_Item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.item"
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="log_contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.contract"
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="log_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.section"
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
