# Generated by Django 4.2 on 2024-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0016_alter_logs_log_item_alter_logs_log_contract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="additional_fees_percentage",
            field=models.FloatField(default=6.5),
        ),
        migrations.AddField(
            model_name="contract",
            name="gross_contract",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="net_contract",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="sum_of_items",
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
