# Generated by Django 4.2 on 2024-08-07 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0017_contract_additional_fees_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="gross_contract",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="net_contract",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="sum_of_items",
        ),
    ]
