# Generated by Django 4.2 on 2024-08-07 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0018_remove_contract_gross_contract_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="additional_fees_percentage",
        ),
    ]
