# Generated by Django 4.2 on 2024-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0019_remove_contract_additional_fees_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="additional_fee_percentage",
            field=models.FloatField(default=6.5),
        ),
    ]
