# Generated by Django 4.2 on 2024-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0021_alter_item_unit_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[("Std", "Std"), ("Psch", "Psch"), ("Stk", "Stk")],
                default="Std",
                max_length=10,
            ),
        ),
    ]
