# Generated by Django 4.2 on 2024-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0024_alter_invoice_amount_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_gross",
            field=models.FloatField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
