# Generated by Django 4.2 on 2024-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0026_contract_vat_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="vat_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=19.0, max_digits=5, null=True
            ),
        ),
    ]
