# Generated by Django 4.2 on 2024-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0027_alter_contract_vat_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("SR", "Schlussrechnung"), ("AR", "Abschlagsrechnung")],
                default="AR",
                max_length=2,
            ),
        ),
    ]
