# Generated by Django 4.2 on 2024-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0028_invoice_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_override",
            field=models.BooleanField(
                default=False,
                help_text="Allow unrestricted date selection in log entries.",
            ),
        ),
    ]
