# Generated by Django 4.2 on 2024-11-15 14:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0029_employee_date_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
