# Generated by Django 4.2 on 2024-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0030_client_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
