# Generated by Django 4.2 on 2025-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0032_estimateinvoicesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimateinvoicesettings",
            name="selected_terms",
        ),
    ]
