# Generated by Django 4.2 on 2025-01-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0033_remove_estimateinvoicesettings_selected_terms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimateinvoicesettings",
            name="terms_and_conditions_files",
        ),
        migrations.CreateModel(
            name="TermsAndConditionsFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="terms_and_conditions/")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_and_conditions_files",
                        to="tracker.estimateinvoicesettings",
                    ),
                ),
            ],
        ),
    ]
