# Generated by Django 4.2 on 2025-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0034_remove_estimateinvoicesettings_terms_and_conditions_files_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termsandconditionsfile",
            name="settings",
        ),
        migrations.AddField(
            model_name="estimateinvoicesettings",
            name="terms_and_conditions_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Upload multiple Word files for terms and conditions.",
                to="tracker.termsandconditionsfile",
            ),
        ),
    ]
