# Generated by Django 4.2 on 2025-01-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0035_remove_termsandconditionsfile_settings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimateinvoicesettings",
            name="terms_and_conditions_files",
        ),
        migrations.AddField(
            model_name="termsandconditionsfile",
            name="settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms_and_conditions_files",
                to="tracker.estimateinvoicesettings",
            ),
            preserve_default=False,
        ),
    ]
