# Generated by Django 4.2 on 2025-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracker",
            "0036_remove_estimateinvoicesettings_terms_and_conditions_files_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_no",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="termsandconditionsfile",
            name="file",
            field=models.FileField(upload_to="templates/terms_and_conditions/"),
        ),
    ]
