# Generated by Django 4.2 on 2025-01-10 14:12

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0037_contract_contract_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="scope_of_work",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
