# Generated by Django 4.2 on 2025-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0038_contract_scope_of_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="scope_of_work",
            field=models.TextField(blank=True, null=True),
        ),
    ]
