# Generated by Django 4.2 on 2025-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0039_alter_contract_scope_of_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
