# Generated by Django 4.2 on 2025-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0040_alter_client_client_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("excel_file", models.FileField(upload_to="hoai_tables/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
