# Generated by Django 4.2 on 2025-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0041_serviceprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprofile",
            name="no_of_Honarzone",
            field=models.IntegerField(default=5, max_length=10),
        ),
    ]
