# Generated by Django 4.2 on 2025-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0042_serviceprofile_no_of_honarzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprofile",
            name="lp_breakdown",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="serviceprofile",
            name="no_of_Honarzone",
            field=models.IntegerField(default=5),
        ),
    ]
