# Generated by Django 4.2 on 2025-01-31 08:15

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0043_serviceprofile_lp_breakdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprofile",
            name="lp_breakdown",
            field=models.JSONField(default=tracker.models.default_lp_breakdown),
        ),
    ]
