# Generated by Django 4.2 on 2025-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0044_alter_serviceprofile_lp_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutive_start_no",
                    models.IntegerField(
                        default=1,
                        help_text="Starting number for consecutive numbering.",
                    ),
                ),
                (
                    "bck_eng_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/estimates/"
                    ),
                ),
                (
                    "bck_de_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/estimates/"
                    ),
                ),
                (
                    "kost_eng_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/estimates/"
                    ),
                ),
                (
                    "kost_de_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/estimates/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_counter",
                    models.IntegerField(
                        default=1, help_text="Counter for generating invoice numbers."
                    ),
                ),
                (
                    "inv_bck_eng_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/invoices/"
                    ),
                ),
                (
                    "inv_bck_de_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/invoices/"
                    ),
                ),
                (
                    "inv_kost_eng_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/invoices/"
                    ),
                ),
                (
                    "inv_kost_de_template",
                    models.FileField(
                        blank=True, null=True, upload_to="templates/invoices/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="termsandconditionsfile",
            name="settings",
        ),
        migrations.DeleteModel(
            name="EstimateInvoiceSettings",
        ),
        migrations.DeleteModel(
            name="TermsAndConditionsFile",
        ),
    ]
