# Generated by Django 4.2 on 2025-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0045_estimatesettings_invoicesettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("ER", "Einzelrechnung (Individual Invoice)"),
                    ("AR", "Abschlagsrechnung (Partial/Progress Invoice)"),
                    ("SR", "Schlussrechnung (Final Invoice)"),
                    ("ZR", "Anzahlungsrechnung (Advance Payment Invoice)"),
                ],
                default="ER",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
