# Generated by Django 4.2 on 2025-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0046_alter_invoice_invoice_type_alter_invoice_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="hoai_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Std", "Std"),
                    ("Psch", "Psch"),
                    ("Stk", "Stk"),
                    ("%", "%"),
                    ("Monat(e)", "Monat(e)"),
                    ("Tag(e)", "Tag(e)"),
                ],
                default="Std",
                max_length=10,
            ),
        ),
    ]
