# Generated by Django 4.2 on 2025-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0047_contract_hoai_data_alter_item_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="zuschlag_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
