# Generated by Django 4.2 on 2025-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0048_contract_zuschlag_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="zuschlag_value",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
