# Generated by Django 4.2 on 2025-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0049_alter_contract_zuschlag_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedInvoiceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
            ],
        ),
    ]
