# Generated by Django 4.2 on 2025-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0050_deletedinvoicenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_cumulative",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
