# Generated by Django 4.2 on 2025-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0051_invoice_is_cumulative"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatesettings",
            name="architect_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=145,
                help_text="Rate for Architekt/In (Architect)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="computational_architect_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=155,
                help_text="Rate for Computational Architect",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="construction_supervision_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=155,
                help_text="Rate for Bauüberwachung (Construction Supervision)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="construction_technician_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=135,
                help_text="Rate for Bautechniker/In (Construction Technician)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="draftsman_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=115,
                help_text="Rate for Zeichner (Draftsman)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="executive_management_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=250,
                help_text="Rate for Geschäftsführung (Executive Management)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="project_management_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=165,
                help_text="Rate for Projektleitung (Project Management)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="estimatesettings",
            name="specialist_planner_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=185,
                help_text="Rate for Fachplaner/In (Specialist Planner)",
                max_digits=10,
            ),
        ),
    ]
