# Generated by Django 4.2 on 2025-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0052_estimatesettings_architect_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="additional_fee_percentage",
            field=models.FloatField(blank=True, default=6.5, null=True),
        ),
    ]
