# Generated by Django 4.2 on 2025-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0053_alter_contract_additional_fee_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date_of_payment",
            field=models.DateField(blank=True, null=True),
        ),
    ]
