# Generated by Django 4.2 on 2025-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0054_invoice_date_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="nachlass_value",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
