# Generated by Django 4.2 on 2025-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0055_contract_nachlass_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="nachlass_percentage",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
