# Generated by Django 4.2 on 2025-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0056_contract_nachlass_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hourly_rates_override",
            field=models.JSONField(
                blank=True, help_text="Custom hourly rates for this project", null=True
            ),
        ),
    ]
