# Generated by Django 4.2 on 2025-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0057_project_hourly_rates_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="exclude_from_nachlass",
            field=models.BooleanField(default=False),
        ),
    ]
