# Generated by Django 4.2 on 2025-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0058_section_exclude_from_nachlass"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="current_invoice_net",
            field=models.FloatField(default=0.0),
        ),
    ]
