# Generated by Django 4.2 on 2025-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0059_invoice_current_invoice_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "InProgress"),
                    ("1", "OnHold"),
                    ("2", "Completed"),
                    ("3", "Discontinued"),
                ],
                max_length=20,
            ),
        ),
    ]
