# Generated by Django 4.2 on 2025-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0060_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_mail",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(default="Unknown Name", max_length=255),
        ),
    ]
