# Generated by Django 4.2 on 2025-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0061_alter_client_client_mail_alter_client_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "InBearbeitung"),
                    ("1", "Zurückgestellt"),
                    ("2", "Abgeschlossen "),
                    ("3", "Eingestellt"),
                ],
                max_length=20,
            ),
        ),
    ]
