# Generated by Django 4.2 on 2025-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0062_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="current_ar_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
